pipeline{
    agent any
    stages{
        stage('build application'){
            steps{
                //add -f for pom.xml path
               sh 'mvn -f pom.xml clean package'
            }
            post{
                success{
                    echo 'Now Archiving ...'
                    archiveArtifacts artifacts : '**/*.war'
                }
            }
        }
    }
    stage('deploying application to staging envirenment'){
        steps{
            build job :  'Deploy_Application_Staging_Env'
        }
       
    }
}